services:
  customers:
    image: microservice-customers:latest
    ports:
      - "8082:8080"
  products:
    image: microservice-products:latest
    ports:
      - "8083:8080"
  orders:
    image: microservice-orders:latest
    environment:
      SERVICE_URL_CUSTOMERS: "http://customers:8080/"
      SERVICE_URL_PRODUCTS: "http://products:8080/"
    ports:
      - "8081:8080"
