apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-orders
  template:
    metadata:
      labels:
        app: microservice-orders
    spec:
      containers:
        - name: microservice-orders
          image: microservice-orders:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_URL_CUSTOMERS
              value: "http://microservice-customers.default.svc.cluster.local:8082/"
            - name: SERVICE_URL_PRODUCTS
              value: "http://microservice-products.default.svc.cluster.local:8083/"
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-orders
spec:
  selector:
    app: microservice-orders
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
